Draft: [ADD] Module Estate/ Estate Account: Exercises of Chapters 12 -14
Emilioglez873/server-framework-101 pull request #2
Opened 2024-10-07 15:32 UTC by Emilioglez873

# Development of chapter 12, 13 and 14 of tutorial server framwork 101 in [Odoo docs ](https://www.odoo.com/documentation/17.0/developer/tutorials/server_framework_101.html)

Model inheritance in res.users to show the properties sell by sales person
Adding method with decorator @ondelete, to prevent deleting properties which are not new or canceled
View inheritance in base.view_users_form to show the field property_ids
Creating link module between estate and account modules
Overriding the action_sold method of estate.property to create an invoice
Adding two invoice lines for each property sold:
- 6% of the selling price
- an additional 100.00 from administrative fees

Adding kanban view for estate.property with grouping by property type

2024-10-07 19:03 UTC, sebasdrk17 commented
@Emilioglez873 rebase please

2024-10-08 13:32 UTC, Emilioglez873 commented
@sebasdrk17  Listo ya hice el rebase y también jale los cambios de master

2024-10-08 20:58 UTC, sebasdrk17 requested changes
Code looks ok, just run pre-commit to check the linter

There are some functional errors that I'll leave in a new comment

2024-10-08 20:58 UTC, sebasdrk17 commented on estate/__manifest__.py
> +
remove extra space

2024-10-08 21:07 UTC, sebasdrk17 commented
# Functional issues:

1. There is an error when trying to install the module I've already solve it but I want you to get the error, to do this drop the database and create a new DB
2. The header options have test names, they should have proper names

![Screenshot 2024-10-08 at 2 59 31 p m](https://github.com/user-attachments/assets/6cab1593-a7af-4853-90ee-6342aaac0d2b)


### Property types

Why does it look like this?

![Screenshot 2024-10-08 at 3 00 43 p m](https://github.com/user-attachments/assets/e495b7af-018d-4a4b-abdb-5daae8560d12)

![Screenshot 2024-10-08 at 3 01 36 p m](https://github.com/user-attachments/assets/a124bc39-5db8-44e8-8f4f-7d9509ec00d3)

2024-10-09 22:11 UTC, sebasdrk17 approved these changes

2024-10-09 22:11 UTC, sebasdrk17 commented
LGTM

2024-10-09 22:12 UTC, sebasdrk17 commented
Remove the draft text from the merge request and use [IMP], we are not adding any modules here

2024-10-10 18:14 UTC, sebasdrk17 commented
@Emilioglez873 

Remember the structure of the commit message: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

In short it should be:

[IMP] estate, estate_account: Exercises of Chapters 12 -14

2024-10-10 18:14 UTC, merged